apiVersion: v1
kind: Secret
metadata:
  name: secretpesbuk
  namespace: staging
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: dG9teTIyNDY=
  DB_NAME: ZGJzb3NtZWQ=
  DB_HOST: ZGItY2lsc3l0b215LmMzd2twbjh6ZXdpcS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=


